export const ROUTER_PATHS = {
  COMMON_SALES: '/common-sales',
  CONTRAGENTS: '/contragents',
  DEPARTURES: '/departures',
  FINANCES: '/finances',
  FIREDWORKERS: '/firedworkers',
  HOME: '/',
  MY_SALES: '/my-sales',
  NOTIFICATIONS: '/notifications',
  PROCUREMENTS: '/procurements',
  SALARY_REPORTS: '/salary-reports',
  SALES_LIST: '/sales-list',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  STRUCTURE: '/structure',
  SUMMARY_TABLE: '/summary-table',
  SUPPLIERS: '/suppliers',
  WORKERS: '/workers',
} as const
