export const ROUTER_PATHS = {
  HOME: '/',
  POLITICS: '/politics',
  OFERTA: '/oferta',
  SIGN_IN: '/sign-in',
  adminLogin: '/admin/login',
  PROFILE: '/profile',
  SIGN_UP: '/sign-up',
  CATALOG: '/catalog',
  ABOUT: '/about',
  CONTACTS: '/contacts',
  DELIVERY: '/delivery',
  SEARCH: '/search',
  CART: '/cart',
  ORDER: '/order',
  PAYMENT_RULES: '/payment-rules',
  RETURNS: '/returns',
  CARE: '/care',
  NEWSLETTER: '/newsletter',
  STORES: '/stores',
  MANUFACTURERS: '/manufacturers',
  ORDER_HISTORY: '/order-history',
  TRACK_ORDER: '/track-order',
  BOOKMARKS: '/bookmarks',
} as const
