export const ROUTER_PATHS = {
  ABOUT: '/about',
  ADMINLOGIN: '/admin/login',
  BOOKMARKS: '/bookmarks',
  CARE: '/care',
  CART: '/cart',
  CATALOG: '/catalog',
  CONTACTS: '/contacts',
  DELIVERY: '/delivery',
  HOME: '/',
  MAIN: '/main',
  MANUFACTURERS: '/manufacturers',
  NEWSLETTER: '/newsletter',
  OFERTA: '/oferta',
  ORDER: '/order',
  ORDER_HISTORY: '/order-history',
  PAYMENT_RULES: '/payment-rules',
  POLITICS: '/politics',
  PROFILE: '/profile',
  RESTOREPASS: '/admin/restore-pass',
  RETURNS: '/returns',
  SEARCH: '/search',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  STORES: '/stores',
  TRACK_ORDER: '/track-order',
} as const
